### PR TITLE
19 course page front end

### PR DESCRIPTION
**Pull request by mariambasem**
this impelented  both courses pages and jobs page fakes issues #18 #19 this branch has the code for courses and jobs

### CODE REVIEW

**Comment by Hana-ElGabry** [comment]
approved but it may need some fixes to better integrate with the system, have a look at it @Hana-ElGabry @bubbup

**Review by Hana-ElGabry — COMMENTED** [review]
review done

**Comment by mariambasem** [comment]
[testcase3.docx](https://github.com/user-attachments/files/18218770/testcase3.docx)

**Comment by mariambasem** [comment]
[testcase3 (1).docx](https://github.com/user-attachments/files/18218787/testcase3.1.docx)

**Comment by mariambasem** [comment]
#21 this implented test cases for many functions

**Pull request merged**
